# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recently_played.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='recently_played.proto',
  package='spotify',
  syntax='proto2',
  serialized_pb=_b('\n\x15recently_played.proto\x12\x07spotify\"P\n\x0crecent_album\x12\r\n\x05\x61lbum\x18\x01 \x02(\t\x12\r\n\x05track\x18\x02 \x02(\t\x12\x11\n\ttimestamp\x18\x04 \x02(\x05\x12\x0f\n\x07unknown\x18\x05 \x02(\x05\"A\n\x0crecent_track\x12\r\n\x05track\x18\x01 \x02(\t\x12\x11\n\ttimestamp\x18\x02 \x02(\x05\x12\x0f\n\x07unknown\x18\x03 \x02(\x05\"U\n\x0frecently_played\x12 \n\x01\x61\x18\x01 \x03(\x0b\x32\x15.spotify.recent_album\x12 \n\x01t\x18\x02 \x03(\x0b\x32\x15.spotify.recent_track')
)




_RECENT_ALBUM = _descriptor.Descriptor(
  name='recent_album',
  full_name='spotify.recent_album',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='album', full_name='spotify.recent_album.album', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='track', full_name='spotify.recent_album.track', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='spotify.recent_album.timestamp', index=2,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unknown', full_name='spotify.recent_album.unknown', index=3,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=114,
)


_RECENT_TRACK = _descriptor.Descriptor(
  name='recent_track',
  full_name='spotify.recent_track',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='track', full_name='spotify.recent_track.track', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='spotify.recent_track.timestamp', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unknown', full_name='spotify.recent_track.unknown', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=181,
)


_RECENTLY_PLAYED = _descriptor.Descriptor(
  name='recently_played',
  full_name='spotify.recently_played',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='spotify.recently_played.a', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t', full_name='spotify.recently_played.t', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=268,
)

_RECENTLY_PLAYED.fields_by_name['a'].message_type = _RECENT_ALBUM
_RECENTLY_PLAYED.fields_by_name['t'].message_type = _RECENT_TRACK
DESCRIPTOR.message_types_by_name['recent_album'] = _RECENT_ALBUM
DESCRIPTOR.message_types_by_name['recent_track'] = _RECENT_TRACK
DESCRIPTOR.message_types_by_name['recently_played'] = _RECENTLY_PLAYED
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

recent_album = _reflection.GeneratedProtocolMessageType('recent_album', (_message.Message,), dict(
  DESCRIPTOR = _RECENT_ALBUM,
  __module__ = 'recently_played_pb2'
  # @@protoc_insertion_point(class_scope:spotify.recent_album)
  ))
_sym_db.RegisterMessage(recent_album)

recent_track = _reflection.GeneratedProtocolMessageType('recent_track', (_message.Message,), dict(
  DESCRIPTOR = _RECENT_TRACK,
  __module__ = 'recently_played_pb2'
  # @@protoc_insertion_point(class_scope:spotify.recent_track)
  ))
_sym_db.RegisterMessage(recent_track)

recently_played = _reflection.GeneratedProtocolMessageType('recently_played', (_message.Message,), dict(
  DESCRIPTOR = _RECENTLY_PLAYED,
  __module__ = 'recently_played_pb2'
  # @@protoc_insertion_point(class_scope:spotify.recently_played)
  ))
_sym_db.RegisterMessage(recently_played)


# @@protoc_insertion_point(module_scope)
